### ISSUE TITLE
Generar el archivo de salida

### ISSUE THREAD

**Issue by NataliaMelissa** [Carhuacusma/CC41-TF-Complejidad#4]
El archivo contiene los siguientes datos:
a. Contenedores usados: <Número de Contenedores>
b. Volumen disponible: <Volumen que suman los contenedores> m2
c. Volumen ocupado: <Volumen total ocupado> m2 (<Volumen total
ocupado expresado en porcentaje> %)
d. Cajas a transportar: m
e. Una fila indicando el siguiente mensaje cabecera “Contenedor Formato
Coordenadas Orientacion”
f. Las siguientes m filas representarán a las m cajas colocadas en el/los
contenedor(es), a través de los siguientes datos:
• num, formato, x, y, z, orientación
5/7
i. num: número de contendor donde se encuentra la caja
ii. formato: formato de la caja colocada
iii. x, y, z: posición a partir de la cual se ubica una caja
iv. orientación: número del 1 al 6 indicando una de 6 posibles
orientaciones en l

**Comment by iller15** [comment]
Terminado

**Comment by iller15** [comment]
Terminado
