### ISSUE TITLE
Algoritmo Dante - pseudocódigo

### ISSUE THREAD

**Issue by NataliaMelissa** [Carhuacusma/CC41-TF-Complejidad#9]
Hacer el pseudocódigo del algoritomo Dante para resolver el problema y ponerlo en el informe

**Comment by Carhuacusma** [comment]
Algoritmo Empaquetar(arregloCajas, arregloFormato):
 //Caja: [(n° plancha, orientación, Formato),(x,y,z)]
 //arregloFormato: [[(ID),(Dimensiones)],[...],...]
 //que ID de Formato pueda accederse rápidamente:
 //hash de los IDs
 arrAux = [(x,y,z),(Dimensiones contando orientación)] 
 matriz = [[arrAux],
           [arrAux],
           ...]
//6 ~ numeros de orientaciones
// (A revisar: Cuánto espacio ocuparía repetir datos en la matriz VS tiempo de procesamiento)
